import AppLayout from '@components/AppLayout'

import RootStyleRegistry from '@providers/RootStyleRegistry'
import ReactQueryProvider from '@providers/ReactQueryProvider'
import RecoilRootProvider from '@providers/RecoilRootProvider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <RecoilRootProvider>
            <RootStyleRegistry>
              <AppLayout>{children}</AppLayout>
            </RootStyleRegistry>
          </RecoilRootProvider>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
