import { RecoilRoot } from 'recoil'

import ReactQueryProvider from '@providers/ReactQueryProvider'
import RootStyleRegistry from '@providers/RootStyleRegistry'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <RecoilRoot>
            <RootStyleRegistry>{children}</RootStyleRegistry>
          </RecoilRoot>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
